#gbu_release_node
g: 9.8                      
air_drag_coe:  0.3  
mass: 0.78
area: 0.0036
air_density: 1.225
dt: 0.01
D: 10
target: [23.1065565,120.2105330,30] # Long, Lat, Alt(Releated Alt)
B: 1.2
C: 10
